//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public string Company { get; set; }
        public string ContactName { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public string SecondaryEmail { get; set; }
        public string SecondayMobileNumber { get; set; }
        public string SecondaryPhoneNumber { get; set; }
        public string SecondaryCountry { get; set; }
        public string SecondaryCity { get; set; }
        public string SecondaryAddress { get; set; }
        public string SecondaryPostCode { get; set; }
        public string ProductHolding { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
