//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyHour
    {
        public DailyHour()
        {
            this.WeeklyHours = new HashSet<WeeklyHour>();
            this.WeeklyHours1 = new HashSet<WeeklyHour>();
            this.WeeklyHours2 = new HashSet<WeeklyHour>();
            this.WeeklyHours3 = new HashSet<WeeklyHour>();
            this.WeeklyHours4 = new HashSet<WeeklyHour>();
            this.WeeklyHours5 = new HashSet<WeeklyHour>();
            this.WeeklyHours6 = new HashSet<WeeklyHour>();
        }
    
        public int Id { get; set; }
        public Nullable<double> TotalHours { get; set; }
        public Nullable<bool> hasOptional { get; set; }
        public Nullable<short> TotalOptionalHours { get; set; }
        public string RegularStart { get; set; }
        public string RegularFinish { get; set; }
        public string OptionalStart { get; set; }
        public string OptionalEnd { get; set; }
        public string AllottedLunchTime { get; set; }
    
        public virtual ICollection<WeeklyHour> WeeklyHours { get; set; }
        public virtual ICollection<WeeklyHour> WeeklyHours1 { get; set; }
        public virtual ICollection<WeeklyHour> WeeklyHours2 { get; set; }
        public virtual ICollection<WeeklyHour> WeeklyHours3 { get; set; }
        public virtual ICollection<WeeklyHour> WeeklyHours4 { get; set; }
        public virtual ICollection<WeeklyHour> WeeklyHours5 { get; set; }
        public virtual ICollection<WeeklyHour> WeeklyHours6 { get; set; }
    }
}
