//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngineerSkill
    {
        public int Id { get; set; }
        public Nullable<int> W6Key { get; set; }
        public Nullable<int> SkillKey { get; set; }
        public Nullable<int> level { get; set; }
    
        public virtual Skill Skill { get; set; }
    }
}
