//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engineer
    {
        public Engineer()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Engineer_ID { get; set; }
        public string Name { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public Nullable<int> Skill { get; set; }
        public Nullable<int> WorkingHours { get; set; }
        public Nullable<short> AllottedVacationDays { get; set; }
        public string VacationStart { get; set; }
        public string VacationEnd { get; set; }
        public Nullable<short> AllottedSickDays { get; set; }
    
        public virtual WeeklyHour WeeklyHour { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
