//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyHour
    {
        public WeeklyHour()
        {
            this.Engineers = new HashSet<Engineer>();
        }
    
        public int Id { get; set; }
        public Nullable<double> WeeklyHours { get; set; }
        public Nullable<int> Monday { get; set; }
        public Nullable<int> Tuesday { get; set; }
        public Nullable<int> Wednesday { get; set; }
        public Nullable<int> Thursday { get; set; }
        public Nullable<int> Friday { get; set; }
        public Nullable<int> Saturday { get; set; }
        public Nullable<int> Sunday { get; set; }
    
        public virtual DailyHour DailyHour { get; set; }
        public virtual DailyHour DailyHour1 { get; set; }
        public virtual DailyHour DailyHour2 { get; set; }
        public virtual DailyHour DailyHour3 { get; set; }
        public virtual DailyHour DailyHour4 { get; set; }
        public virtual DailyHour DailyHour5 { get; set; }
        public virtual DailyHour DailyHour6 { get; set; }
        public virtual ICollection<Engineer> Engineers { get; set; }
    }
}
